// <auto-generated />
using System;
using FinanceApp.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818000000_AddShowInNavigationToMarketIndex")]
    partial class AddShowInNavigationToMarketIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AsOfDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CashAndEquivalents")
                        .HasColumnType("decimal(28,2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("EbitdaTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("EnterpriseValue")
                        .HasColumnType("decimal(28,2)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ForwardPeRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FreeCashFlowTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("NetIncomeTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("OperatingIncomeTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("PbRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PeRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RevenueTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Yahoo Finance");

                    b.Property<string>("SourceSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalDebt")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("decimal(28,2)");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("FundamentalsSnapshots");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Dividend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.EarningsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("Unknown");

                    b.Property<decimal?>("EpsEstimate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EpsReported")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FiscalPeriod")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReportDateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("RevenueEstimate")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("RevenueReported")
                        .HasColumnType("decimal(28,2)");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Yahoo Finance");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "ReportDate", "FiscalPeriod")
                        .IsUnique();

                    b.ToTable("EarningsEvents");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.FinancialPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AsOfDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Ebitda")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("EpsEstimate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EpsReported")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FiscalQuarter")
                        .HasColumnType("int");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("FreeCashFlow")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("OperatingIncome")
                        .HasColumnType("decimal(28,2)");

                    b.Property<DateTime?>("PeriodEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ReportedCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(28,2)");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Yahoo Finance");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalDebt")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("decimal(28,2)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "PeriodType", "PeriodEndDate")
                        .IsUnique();

                    b.ToTable("FinancialPeriods");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SectorId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.MarketIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CountryOrRegion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProviderSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("ShowInNavigation")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique();

                    b.ToTable("MarketIndices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DJIA",
                            CountryOrRegion = "USA",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Индекс Доу-Джонса для промышленных компаний отражает динамику 30 крупнейших публичных компаний США. Взвешен по цене, а не по рыночной капитализации, что является методологическим ограничением: более дорогие акции оказывают непропорционально большое влияние. Используется как исторический барометр состояния американской экономики, однако из-за малого числа компонентов и ценового взвешивания считается менее репрезентативным, чем S&P 500.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "Dow Jones Industrial Average",
                            NormalizedCode = "DJIA",
                            NormalizedName = "DOW JONES INDUSTRIAL AVERAGE",
                            ProviderSymbol = "^DJI",
                            SortOrder = 10,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "SPX",
                            CountryOrRegion = "USA",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по рыночной капитализации индекс 500 крупнейших публичных компаний США. Широко признан эталоном для американского рынка акций и базой для большинства пассивных инвестиционных стратегий. Охватывает около 80% совокупной капитализации рынка США. Основное ограничение — концентрация в технологическом секторе и крупнейших компаниях. Состав и методологию определяет комитет S&P.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "S&P 500",
                            NormalizedCode = "SPX",
                            NormalizedName = "S&P 500",
                            ProviderSymbol = "^GSPC",
                            SortOrder = 20,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "COMP",
                            CountryOrRegion = "USA",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по капитализации индекс всех акций, торгующихся на бирже NASDAQ, — преимущественно технологических и растущих компаний. Включает более 3 000 ценных бумаг. Высокая концентрация в IT-секторе делает его чувствительным к изменениям процентных ставок и настроениям в отношении акций роста.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "NASDAQ Composite",
                            NormalizedCode = "COMP",
                            NormalizedName = "NASDAQ COMPOSITE",
                            ProviderSymbol = "^IXIC",
                            SortOrder = 30,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Code = "NDX",
                            CountryOrRegion = "USA",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по капитализации индекс 100 крупнейших нефинансовых компаний, котирующихся на NASDAQ. Концентрация в технологии, потребительском секторе и здравоохранении делает его популярным инструментом для ставки на инновационные компании. Отсутствие финансового сектора — ключевое отличие от широкого рынка.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "NASDAQ-100",
                            NormalizedCode = "NDX",
                            NormalizedName = "NASDAQ-100",
                            ProviderSymbol = "^NDX",
                            SortOrder = 40,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Code = "RUT",
                            CountryOrRegion = "USA",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Индекс 2 000 компаний малой капитализации из Russell 3000. Традиционно используется как барометр внутреннего экономического здоровья США: малые компании менее зависимы от глобальных цепочек поставок. Отличается более высокой волатильностью и менее ликвидным составом по сравнению с крупнокапитализированными индексами.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "Russell 2000",
                            NormalizedCode = "RUT",
                            NormalizedName = "RUSSELL 2000",
                            ProviderSymbol = "^RUT",
                            SortOrder = 50,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Code = "UKX",
                            CountryOrRegion = "UK",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по капитализации индекс 100 крупнейших компаний Лондонской фондовой биржи. Значительную долю занимают горнодобывающие, энергетические и финансовые компании с глобальными операциями. Существенная часть выручки компонентов поступает из-за рубежа, поэтому индекс реагирует на курс фунта стерлингов.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "FTSE 100",
                            NormalizedCode = "UKX",
                            NormalizedName = "FTSE 100",
                            ProviderSymbol = "^FTSE",
                            SortOrder = 60,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Code = "DAX",
                            CountryOrRegion = "Germany",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по капитализации индекс 40 крупнейших немецких компаний на бирже Xetra. Является главным барометром германского и, косвенно, европейского промышленного сектора. Особенность: DAX — индекс совокупного дохода (total return), включающий реинвестированные дивиденды, что делает его напрямую несопоставимым с price-return индексами.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "DAX",
                            NormalizedCode = "DAX",
                            NormalizedName = "DAX",
                            ProviderSymbol = "^GDAXI",
                            SortOrder = 70,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Code = "PX1",
                            CountryOrRegion = "France",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по капитализации (free-float) индекс 40 крупнейших компаний Парижской фондовой биржи Euronext. Репрезентирует французский рынок и отражает широкий спектр отраслей: предметы роскоши, энергетика, финансы, промышленность. Многие компоненты являются глобальными корпорациями, поэтому чувствительны к валютным курсам.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "CAC 40",
                            NormalizedCode = "PX1",
                            NormalizedName = "CAC 40",
                            ProviderSymbol = "^FCHI",
                            SortOrder = 80,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Code = "SX5E",
                            CountryOrRegion = "Eurozone",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 50 крупнейших компаний еврозоны из 8 стран. Широко используется как базовый актив для деривативов и ETF, ориентированных на европейский рынок. Концентрация в нескольких странах (Франция, Германия) и секторах (финансы, промышленность) ограничивает диверсификацию.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "EURO STOXX 50",
                            NormalizedCode = "SX5E",
                            NormalizedName = "EURO STOXX 50",
                            ProviderSymbol = "^STOXX50E",
                            SortOrder = 90,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Code = "SXXP",
                            CountryOrRegion = "Europe",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 600 компаний из 17 европейских стран, включая страны вне еврозоны (Великобритания, Швейцария, Скандинавия). Обеспечивает более широкое географическое и секторальное покрытие Европы, чем EURO STOXX 50. Применяется как эталон для паневропейских стратегий.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "STOXX Europe 600",
                            NormalizedCode = "SXXP",
                            NormalizedName = "STOXX EUROPE 600",
                            ProviderSymbol = "^STOXX",
                            SortOrder = 100,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Code = "SMI",
                            CountryOrRegion = "Switzerland",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 20 крупнейших компаний Швейцарской биржи. Сильно сконцентрирован в фармацевтике, финансах и товарах повседневного спроса. Выражен в швейцарских франках, которые традиционно считаются защитным активом. Высокая отраслевая концентрация является ключевым ограничением индекса.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "SMI",
                            NormalizedCode = "SMI",
                            NormalizedName = "SMI",
                            ProviderSymbol = "^SSMI",
                            SortOrder = 110,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Code = "IBEX",
                            CountryOrRegion = "Spain",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 35 наиболее ликвидных акций Испанской фондовой биржи. Значительную долю занимают банки, телекоммуникационные и энергетические компании. Индекс чувствителен к динамике кредитного рынка еврозоны и политической обстановке.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "IBEX 35",
                            NormalizedCode = "IBEX",
                            NormalizedName = "IBEX 35",
                            ProviderSymbol = "^IBEX",
                            SortOrder = 120,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Code = "FTSEMIB",
                            CountryOrRegion = "Italy",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 40 крупнейших и наиболее ликвидных итальянских компаний. Существенный вес имеют финансовый и коммунальный секторы. Высокая концентрация в банках делает индекс особенно чувствительным к ситуации с государственным долгом Италии.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "FTSE MIB",
                            NormalizedCode = "FTSEMIB",
                            NormalizedName = "FTSE MIB",
                            ProviderSymbol = "FTSEMIB.MI",
                            SortOrder = 130,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Code = "NKY",
                            CountryOrRegion = "Japan",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ценово-взвешенный индекс 225 избранных акций Токийской фондовой биржи — аналог Доу-Джонса для японского рынка. Является наиболее известным барометром японского фондового рынка. Ценовое взвешивание создаёт те же искажения, что и в DJIA: высокостоимостные акции оказывают непропорциональное влияние.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "Nikkei 225",
                            NormalizedCode = "NKY",
                            NormalizedName = "NIKKEI 225",
                            ProviderSymbol = "^N225",
                            SortOrder = 140,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Code = "TPX",
                            CountryOrRegion = "Japan",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс всех акций первой секции Токийской фондовой биржи — более 2 000 компаний. Считается более репрезентативным отражением японского рынка, чем Nikkei 225. Используется японскими институциональными инвесторами как основной эталон.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "TOPIX",
                            NormalizedCode = "TPX",
                            NormalizedName = "TOPIX",
                            ProviderSymbol = "^TOPX",
                            SortOrder = 150,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Code = "HSI",
                            CountryOrRegion = "Hong Kong",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс крупнейших компаний Гонконгской фондовой биржи. Включает компании из материкового Китая, котирующиеся в Гонконге (акции H). Чувствителен к регуляторной политике материкового Китая и геополитическим рискам. Методология и состав регулярно пересматриваются.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "Hang Seng Index",
                            NormalizedCode = "HSI",
                            NormalizedName = "HANG SENG INDEX",
                            ProviderSymbol = "^HSI",
                            SortOrder = 160,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Code = "CSI300",
                            CountryOrRegion = "China",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 300 крупнейших акций, торгующихся на Шанхайской и Шэньчжэньской биржах (акции А). Отражает динамику китайского внутреннего рынка, доступного через механизмы Stock Connect. Подвержен влиянию регуляторных изменений и ограничений на движение капитала.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "CSI 300",
                            NormalizedCode = "CSI300",
                            NormalizedName = "CSI 300",
                            ProviderSymbol = "000300.SS",
                            SortOrder = 170,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Code = "SHCOMP",
                            CountryOrRegion = "China",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по капитализации индекс всех акций А и Б, котирующихся на Шанхайской фондовой бирже. Используется как широкий барометр китайского рынка, однако включает большое число малоликвидных компаний. Доступ иностранных инвесторов ограничен квотами и регуляторными требованиями.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "Shanghai Composite",
                            NormalizedCode = "SHCOMP",
                            NormalizedName = "SHANGHAI COMPOSITE",
                            ProviderSymbol = "000001.SS",
                            SortOrder = 180,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Code = "AS51",
                            CountryOrRegion = "Australia",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 200 крупнейших компаний Австралийской фондовой биржи. Сильно сконцентрирован в финансовом и горнодобывающем секторах. Динамика тесно связана с ценами на сырьё и торговыми отношениями с Китаем. Стандартный эталон для австралийских портфельных стратегий.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "S&P/ASX 200",
                            NormalizedCode = "AS51",
                            NormalizedName = "S&P/ASX 200",
                            ProviderSymbol = "^AXJO",
                            SortOrder = 190,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Code = "SPTSX",
                            CountryOrRegion = "Canada",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по рыночной капитализации индекс всех компаний, удовлетворяющих критериям включения Торонтской фондовой биржи. Существенную долю занимают финансовый сектор, горнодобыча и нефтегазовая промышленность. Динамика коррелирует с ценами на сырьё. Основной эталон канадского рынка акций.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "S&P/TSX Composite",
                            NormalizedCode = "SPTSX",
                            NormalizedName = "S&P/TSX COMPOSITE",
                            ProviderSymbol = "^GSPTSE",
                            SortOrder = 200,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Code = "SENSEX",
                            CountryOrRegion = "India",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ценово-взвешенный индекс 30 хорошо зарекомендовавших себя компаний Бомбейской фондовой биржи. Один из старейших индикаторов индийского рынка. Малое число компонентов ограничивает репрезентативность. Чувствителен к изменениям в регуляторной среде, процентным ставкам Резервного банка Индии и состоянию банковского сектора.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "BSE SENSEX",
                            NormalizedCode = "SENSEX",
                            NormalizedName = "BSE SENSEX",
                            ProviderSymbol = "^BSESN",
                            SortOrder = 210,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Code = "NIFTY50",
                            CountryOrRegion = "India",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс 50 крупнейших компаний Национальной фондовой биржи Индии. Охватывает 13 секторов и считается более репрезентативным эталоном индийского рынка, чем SENSEX. Широко используется как база для деривативов и пассивных инструментов.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "NIFTY 50",
                            NormalizedCode = "NIFTY50",
                            NormalizedName = "NIFTY 50",
                            ProviderSymbol = "^NSEI",
                            SortOrder = 220,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Code = "KOSPI",
                            CountryOrRegion = "South Korea",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по рыночной капитализации индекс всех акций обыкновенных акций Корейской фондовой биржи. Существенную долю занимают технологические и автомобильные конгломераты. Чувствителен к геополитическим рискам на Корейском полуострове и глобальному спросу на полупроводники.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "KOSPI",
                            NormalizedCode = "KOSPI",
                            NormalizedName = "KOSPI",
                            ProviderSymbol = "^KS11",
                            SortOrder = 230,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Code = "IBOV",
                            CountryOrRegion = "Brazil",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по ликвидности торгов индекс наиболее торгуемых акций биржи B3. Высокую долю занимают финансовые, сырьевые и энергетические компании. Подвержен влиянию бразильского реала, политических рисков и мировых цен на commodities. Является основным эталоном бразильского рынка акций.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "Bovespa (IBOVESPA)",
                            NormalizedCode = "IBOV",
                            NormalizedName = "BOVESPA (IBOVESPA)",
                            ProviderSymbol = "^BVSP",
                            SortOrder = 240,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Code = "MSCIW",
                            CountryOrRegion = "Developed Markets",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс акций крупной и средней капитализации из более 20 развитых стран. Охватывает около 85% рынка с поправкой на free-float в каждой стране. Широко используется как глобальный эталон для развитых рынков. Высокая доля США (более 60%) является ключевым ограничением географической диверсификации.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "MSCI World",
                            NormalizedCode = "MSCIW",
                            NormalizedName = "MSCI WORLD",
                            SortOrder = 250,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Code = "MSCIEM",
                            CountryOrRegion = "Emerging Markets",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс акций крупной и средней капитализации из более 20 развивающихся стран. Охватывает около 85% рынка с поправкой на free-float в каждой стране. Отражает возможности роста развивающихся экономик, но несёт повышенные риски: валютные, политические и ликвидности.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "MSCI Emerging Markets",
                            NormalizedCode = "MSCIEM",
                            NormalizedName = "MSCI EMERGING MARKETS",
                            SortOrder = 260,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Code = "MSCIACWI",
                            CountryOrRegion = "Global",
                            CreatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Взвешенный по free-float капитализации индекс акций крупной и средней капитализации из 47 стран — как развитых, так и развивающихся рынков. Объединяет MSCI World и MSCI Emerging Markets. Используется как единый глобальный эталон. Высокая доля США сохраняется и в ACWI.",
                            IsArchived = false,
                            ShowInNavigation = true,
                            Name = "MSCI ACWI",
                            NormalizedCode = "MSCIACWI",
                            NormalizedName = "MSCI ACWI",
                            SortOrder = 270,
                            UpdatedAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FinanceApp.Core.Models.MarketIndexHistoricalPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("MarketIndexId")
                        .HasColumnType("int");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ProviderSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MarketIndexId", "Interval", "Timestamp");

                    b.HasIndex("MarketIndexId", "Timestamp", "Interval")
                        .IsUnique();

                    b.ToTable("MarketIndexHistoricalPrices");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("StopMarket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BrokerCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashBalanceAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CurrentPriceAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CurrentPriceChange")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CurrentPriceChangePercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("NYSE");

                    b.Property<string>("FinanzenNetSlug")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Wkn")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("TrackingStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProviderSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasFilter("`Isin` IS NOT NULL");

                    b.HasIndex("Wkn")
                        .IsUnique()
                        .HasFilter("`Wkn` IS NOT NULL");

                    b.HasIndex("TrackingStatus")
                        .HasDatabaseName("IX_Stocks_TrackingStatus");

                    b.HasIndex("ProviderSymbol")
                        .HasDatabaseName("IX_Stocks_ProviderSymbol")
                        .HasFilter("`ProviderSymbol` IS NOT NULL");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.StockHistoricalPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FinancialCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NormalizedQuoteCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("QuoteCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("QuoteUnitMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(1m);

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Volume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Timestamp");

                    b.HasIndex("StockId", "Timestamp", "Interval")
                        .IsUnique();

                    b.ToTable("StockHistoricalPrices");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.StockMarketIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("MarketIndexId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderConstituentKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("MarketIndexId");

                    b.HasIndex("StockId", "MarketIndexId")
                        .HasDatabaseName("IX_StockMarketIndices_StockId_MarketIndexId");

                    b.ToTable("StockMarketIndices");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("InstrumentCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("InstrumentCodeType")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SignedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("`OrderId` IS NOT NULL");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Dividend", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Dividends")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.EarningsEvent", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", "Snapshot")
                        .WithMany("EarningsEvents")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.FinancialPeriod", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", "Snapshot")
                        .WithMany("Periods")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Industry", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Sector", "Sector")
                        .WithMany("Industries")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.MarketIndexHistoricalPrice", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.MarketIndex", "MarketIndex")
                        .WithMany()
                        .HasForeignKey("MarketIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketIndex");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Order", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Orders")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Portfolio", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.PortfolioItem", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Items")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Stock", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Industry", "Industry")
                        .WithMany("Stocks")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.StockHistoricalPrice", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.StockMarketIndex", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.MarketIndex", "MarketIndex")
                        .WithMany("StockMarketIndices")
                        .HasForeignKey("MarketIndexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany("MarketIndices")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketIndex");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Transaction", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", b =>
                {
                    b.Navigation("EarningsEvents");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Industry", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.MarketIndex", b =>
                {
                    b.Navigation("StockMarketIndices");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Portfolio", b =>
                {
                    b.Navigation("Dividends");

                    b.Navigation("Items");

                    b.Navigation("Orders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Sector", b =>
                {
                    b.Navigation("Industries");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Stock", b =>
                {
                    b.Navigation("MarketIndices");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.User", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
