// <auto-generated />
using System;
using FinanceApp.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814192726_AddNormalizedUserAuth")]
    partial class AddNormalizedUserAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AsOfDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CashAndEquivalents")
                        .HasColumnType("decimal(28,2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("EbitdaTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("EnterpriseValue")
                        .HasColumnType("decimal(28,2)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ForwardPeRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FreeCashFlowTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("NetIncomeTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("OperatingIncomeTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("PbRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PeRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RevenueTtm")
                        .HasColumnType("decimal(28,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Yahoo Finance");

                    b.Property<string>("SourceSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalDebt")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("decimal(28,2)");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("FundamentalsSnapshots");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Dividend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.EarningsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("Unknown");

                    b.Property<decimal?>("EpsEstimate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EpsReported")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FiscalPeriod")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReportDateEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("RevenueEstimate")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("RevenueReported")
                        .HasColumnType("decimal(28,2)");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Yahoo Finance");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "ReportDate", "FiscalPeriod")
                        .IsUnique();

                    b.ToTable("EarningsEvents");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.FinancialPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AsOfDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Ebitda")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("EpsEstimate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EpsReported")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FiscalQuarter")
                        .HasColumnType("int");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("FreeCashFlow")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("OperatingIncome")
                        .HasColumnType("decimal(28,2)");

                    b.Property<DateTime?>("PeriodEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ReportedCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(28,2)");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("Yahoo Finance");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalDebt")
                        .HasColumnType("decimal(28,2)");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("decimal(28,2)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "PeriodType", "PeriodEndDate")
                        .IsUnique();

                    b.ToTable("FinancialPeriods");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("StopMarket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BrokerCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashBalanceAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CurrentPriceAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CurrentPriceChange")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CurrentPriceChangePercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("NYSE");

                    b.Property<string>("FinanzenNetSlug")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Wkn")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasFilter("`Isin` IS NOT NULL");

                    b.HasIndex("Wkn")
                        .IsUnique()
                        .HasFilter("`Wkn` IS NOT NULL");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.StockHistoricalPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FinancialCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NormalizedQuoteCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("QuoteCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("QuoteUnitMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(1m);

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Volume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Timestamp");

                    b.HasIndex("StockId", "Timestamp", "Interval")
                        .IsUnique();

                    b.ToTable("StockHistoricalPrices");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("InstrumentCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("InstrumentCodeType")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SignedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("`OrderId` IS NOT NULL");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Dividend", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Dividends")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.EarningsEvent", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", "Snapshot")
                        .WithMany("EarningsEvents")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.FinancialPeriod", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", "Snapshot")
                        .WithMany("Periods")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Order", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Orders")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Portfolio", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.PortfolioItem", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Items")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.StockHistoricalPrice", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Transaction", b =>
                {
                    b.HasOne("FinanceApp.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.CompanyFundamentalsSnapshot", b =>
                {
                    b.Navigation("EarningsEvents");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.Portfolio", b =>
                {
                    b.Navigation("Dividends");

                    b.Navigation("Items");

                    b.Navigation("Orders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceApp.Core.Models.User", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
